#! /bin/bash

#----------------------------------------------------------------------
# Description: the official Linux x86-64 Firefox distribution updater
#              Allows you to update Firefox from command line/CLI/terminal
#
# Author: Artem S. Tashkinov
# Created at: Wed Dec 20 13:50 +05 2017
#             Thu Dec 21 13:08 +05 2017 - remove hard coded values & update channel
# Computer: localhost.localdomain
# System: Linux 4.14.3-300.fc27.x86_64 on x86_64
#
# Copyright (c) 2017 Artem S. Tashkinov  All rights reserved.
#----------------------------------------------------------------------

# See the list of available languages here: https://ftp.mozilla.org/pub/firefox/releases/latest/README.txt
lang=en-US

diewithmsg()
{
    echo "ERROR: $1"
    exit 1
}

sanitychecker()
{
    test -z "$1" && diewithmsg "Empty version string. Perhaps this script needs to be updated."
    result=`echo "$1" | sed 's/\.//g;s/b//;s/[0-9]//g'`
    test -n "$result" && diewithmsg "The version string [$1] is wrong."
}

test -z "$2" && diewithmsg "Usage is: `basename "$0"` user_for_update firefox_installation_directory channel[beta or empty for stable]"
grep -qw "$1" /etc/passwd || diewithmsg "Unable to find the user '$1'"
test -f "$2/firefox" || diewithmsg "'$2' is not a valid Firefox installation directory"

usersafe="$1"
dfirefox="$2"
channel="$3"

id=`id -u` || diewithmsg "id failed!"

if [ "$id" == "0" ]; then
    realuser=`stat -c '%U' "$dfirefox"` || diewithmsg "Stat has failed."
    if [ "$realuser" != "$usersafe" ]; then
        echo -n "Applying permissions $usersafe:$usersafe for '$2' ... "
        chown -R "$usersafe:$usersafe" "$dfirefox" && echo OK || diewithmsg "This mustn't happen."
    fi
    echo -n "Dropping root privileges ... "
    sudo -u "$usersafe" "$0" "$usersafe" "$dfirefox" "$channel"
    exit $?
fi

echo "OK"
echo "Running as user '$USER'."

if [ "$channel" == "beta" ]; then
    echo "Selected beta update channel"
    channel="-beta" 
else
    echo "Selected stable update channel"
    channel=""
fi

echo -n "Installed version: "
versionhave=`grep -a '<label id="version">' "$dfirefox/browser/omni.ja"  | sed 's/.*version">\(.*\)<\/label.*/\1/'`
sanitychecker "$versionhave"
echo "$versionhave"

echo -n "Available version: "
versionnext=`wget --spider "https://download.mozilla.org/?product=firefox$channel-latest&os=linux64&lang=$lang" 2>&1 | grep Location | sed 's/.*releases\/\(.*\)\/linux.*/\1/'`
sanitychecker "$versionnext"
echo "$versionnext"

test "$versionhave" == "$versionnext" && echo "You're up to date. Exiting." && exit 0

workdir=`mktemp -d`
test -d "$workdir" || die "Unable to create a working directory"
cd "$workdir" || diewithmsg "Unable to enter a working directory"

mar="firefox-$versionhave-$versionnext.partial.mar"
url="https://ftp.mozilla.org/pub/firefox/releases/$versionnext/update/linux-x86_64/en-US/$mar"
echo -n "Downloading delta from $versionhave to $versionnext [$url] ... "
wget -q "$url" && echo "OK" || diewithmsg "wget failed"
mv "$mar" "update.mar" || diewithmsg "Renaming of $mar failed"

echo "Applying update ..."
LD_LIBRARY_PATH="$dfirefox" "$dfirefox/updater" "$workdir" "$dfirefox" "$dfirefox"

echo -n "Cleaning up ... "
rm -rf "$workdir" && echo OK

echo "All done"
