#! /bin/bash

# 2020-08-21 08:12:07 didn't sleep until 10am
# 2020-08-22 03:34:07 replaced ρ with 🗘

read temp draw fan driver pciev pciew loadgpu loadfb ramused pstate clocksgpu clocksmem plim < <(nvidia-smi \
    --query-gpu=temperature.gpu,power.draw,fan.speed,driver_version,pcie.link.gen.current,pcie.link.width.current,utilization.gpu,utilization.memory,memory.used,pstate,clocks.gr,clocks.mem,power.limit \
    --format=csv,noheader,nounits | sed 's/,//g')

echo "<txt><span weight='normal' fgcolor='#FF5555'>${temp}°</span> <span weight='normal' fgcolor='#00EEEE'>$(printf "%.1f" "$draw" 2>/dev/null)W</span> 🗘 ${fan}</txt>"
echo -e "<tool>GPU load: $loadgpu%\nGPU: $clocksgpu MHz\nFB load: $loadfb%\nGDDR: $clocksmem MHz\nVRAM: $ramused MiB\nPerf: $pstate\nPCI-E: v${pciev} x ${pciew}\nMax: $plim W\nDriver: $driver</tool>"
echo "<txtclick>nvidia-settings</txtclick>"
