#! /bin/bash

# Shows the maximum frequency of all CPU cores in the system
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq | awk '{if (max<$0) max=$0}END{printf "%.2fGHz",max/1000000}'

# Maximum p7zip compression
# mmt4 + 1.5GB dictionary requires 32GB of free(!) RAM
7za a -mx=9 -myx=9 -mfb=273 -bt -slp -mmt4 -md=1536m -mqs archive_name.7z [files or/and directories]

# Compute md5sum for all the files and subdirectoties' files in the current directory
find . -type f -print0 | xargs -0 [nocache] md5sum > output-file.md5

# My favourite rsync invocation (mind the trailing slashes!)
[ionice -c3] [nocache] rsync -avc --progress --preallocate --delete source/ /destination

# My favourite mkfs.ext4/mke2fs invocation
mkfs.ext4 -O ^huge_file,^has_journal /dev/device

# My favourite pv invocation
[nocache] pv -petrab /dev/source | tee /dev/destination | md5sum

# Too tired of remembering all the flags required to launch Google Chrome, originally 2018-03-06 22:47:33
env TZ=USA/Pacific FREETYPE_PROPERTIES=truetype:interpreter-version=35 chrome --disk-cache-dir=/tmp/.chrome-cache "$@"

# Extract a cpio archive
cpio -i -m -d -F "name.cpio"

# Create a cpio archive
find "directory" -depth | cpio -o -H crc -O "name.cpio"
