#! /bin/bash

# apply zip contents time to the zip files itself
# Sat Dec 30 20:29:31 2017

for i in "$@"; do
	if [ -n "`file "$i" 2>&1 | grep 'Zip archive data'`" ]; then
		nd=`unzip -l "$i" | awk '/[0-9][0-9]-..-..../{print $2" "$3}' | sort -n | tail -1 | sed 's/\(..\)-\(..\)-\(....\) \(..\):\(..\)/\3\1\2\4\5/'`
		echo "File '$i', date $nd"
		touch -t "$nd" "$i"
	else
		echo "Skipping file '$i': not a zip file"
	fi
done
